Verification
bohatermateusz/CSV_Converter pull request #1
Opened 2020-09-25 11:12 UTC by bohatermateusz

Code refactorization and optimizations

2020-09-28 11:47 UTC, LukaszRozmej requested changes
Pros:
Good high level separation of concerns. Making smaller clearer classes with single responsibility.

Cons (big ones):
No review supplied in CsvReaderWriter_review.cs,
Read method doesn't do anything useful,
Low level code wasn't fixed

2020-09-28 11:47 UTC, LukaszRozmej commented on InterfacesHub/IReader.cs
> +        bool Read();
What is the point of this method?

2020-09-28 11:47 UTC, LukaszRozmej commented on Interview.Tests/CSVReaderWriterTests.cs
> +
Doesn't actually supply columns collection with meaningful values

2020-09-29 10:55 UTC, bohatermateusz commented
> Pros:
> Good high level separation of concerns. Making smaller clearer classes with single responsibility.
> 
> Cons (big ones):
> No review supplied in CsvReaderWriter_review.cs,
> Read method doesn't do anything useful,
> Low level code wasn't fixed

Comments to CsvReaderWriter_review, was provided here:
https://github.com/bohatermateusz/MyTechTask/commit/aab3eafa4a2243dca6f7b6f53a49b26017130661

You are totally right, Read method doesn't do anything special and it is not doing this for which it was created. I have assumed that code which was written by intern is working(including low level code) and my job is to focus on refactorization. I will fix that.

2020-09-29 10:58 UTC, bohatermateusz commented on InterfacesHub/IReader.cs
> +        bool Read();
Interface might be fine. Implementation of Interface is wrong (which doesn't do anything special)

2020-09-29 10:59 UTC, bohatermateusz commented on Interview.Tests/CSVReaderWriterTests.cs
> +
True

2020-09-29 11:00 UTC, LukaszRozmej commented
bool Read(out string column1, out string column2) was working

2020-09-29 16:59 UTC, bohatermateusz commented
> bool Read(out string column1, out string column2) was working

Ok, I have change both of them to tuple values

2020-12-06 17:48 UTC, merged